name = "vs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "VS_C3_KV"
id = "70fe3a1138d94643b68aaabb138c81b5"

[vars]
FIREBASE_API_KEY = "AIzaSyAUPv7dU2kEk1rdC__6z8aGlPYPfQh_ogA"
FIREBASE_PROJECT = "payperview-7c21f"
